name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh host 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/dart_telegram_bot
            git pull
            pub get
            pm2 stop start.sh
            pm2 start start.sh