name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: garygrossgarten
          privateKey: ${{ secrets.KEY}}
      - name: ls -a via ssh 2
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: garygrossgarten
          privateKey: ${{ secrets.KEY}}
          tryKeyboard: true
      - name: ssh host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd dart_telegram_bot
            git pull
            pub get
            pm2 stop start.sh
            pm2 start start.sh -- ${{ secrets.BOT_KEY }}